apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-staging
  labels:
    {{- include "praxis-form.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-staging-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
