apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: batool
  labels:
    app: backend 
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: {{ .Values.backend.imagePullSecret }}
      containers:
        - name: backend-container
          image: {{ .Values.backend.image }}
          ports:
           - containerPort: 8080
          env:
            - name: MONGODB_URI
              value: mongodb://praxis-form-mongodb.praxis.svc.cluster.local:27017/batoolpraxis
            - name: ADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ADMIN_DEFAULT_PASSWORD
            - name: JWT_EXP_MINUTES
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_EXP_MINUTES
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET



         
