apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: batool
  labels:
    app: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: frontend-container
          image: ghcr.io/batool193/frontend:v1
          ports:
           - containerPort: 80
          env:
            - name: API_URL
              value: "https://batoul.praxis-form.de"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
