kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: batool
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYmF0b29sMTkzIiwicGFzc3dvcmQiOiJnaHBfS2tMVzE3UUVKdGQzS3JhbVY3NkhCTlJwT1FJV0x2M1ZxU3c2IiwiYXV0aCI6IlltRjBiMjlzTVRrek9tZG9jRjlMYTB4WE1UZFJSVXAwWkROTGNtRnRWamMyU0VKT1VuQlBVVWxYVEhZelZuRlRkelk9In19fQ==
type: kubernetes.io/dockerconfigjson
