backend:
  replicas: 3
  imagePullSecret: regcred
  repository:
    image: ghcr.io/batool193/backend
    tag: "v1"
frontend:
  repository:
    image: ghcr.io/batool193/frontend
    tag: "v1"
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    # Values can be templated
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    path: /
    pathType: Prefix

    hosts:
      - batoul-grafana.praxis-form.de

    tls:
      - secretName: grafana-praxis-form-tls
        hosts:
          - batoul-grafana.praxis-form.de

